### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by bakbuz** [kartik-v/strength-meter#22]
Strength Meter Turkish translation.
This file must be saved in UTF-8 encoding.

(function ($) {
    "use strict";

    $.fn.strengthLocales['tr'] = {
        toggleTitle: 'Parolayı göster/gizle',
        verdictTitles: {
            0: 'Çok kısa',
            1: 'Çok zayıf',
            2: 'Zayıf',
            3: 'İyi',
            4: 'Güçlü',
            5: 'Çok güçlü'
        }
    };
})(jQuery);

**Comment by kartik-v** [comment]
Thanks. Can you please submit a pull request for this?

**Comment by bakbuz** [comment]
of course
